In [16]:
%matplotlib inline
import pandas as pd # A beautiful library to help us work with data as tables
import numpy as np # So we can use number matrices. Both pandas and TensorFlow need
import matplotlib.pyplot as plt  # Visualize the things
import tensorflow as tf          # Fire from the gods

#lets print the dataframe to see whats in it..
dataframe = pd.read_csv('data.csv')
# ahh cool TABLESS!!!!!
dataframe

index    area  bathrooms     price    sq_price
0       0  2104.0        3.0  399900.0  190.066540
1       1  1600.0        3.0  329900.0  206.187500
2       2  2400.0        3.0  369000.0  153.750000
3       3  1416.0        2.0  232000.0  163.841808
4       4  3000.0        4.0  539900.0  179.966667
5       5  1985.0        4.0  299900.0  151.083123
6       6  1534.0        3.0  314900.0  205.280313
7       7  1427.0        3.0  198999.0  139.452698
8       8  1380.0        3.0  212000.0  153.623188
9       9  1494.0        3.0  242500.0  162.315930
10     10  1940.0        4.0  239999.0  123.710825
11     11  2000.0        3.0  347000.0  173.500000
12     12  1890.0        3.0  329999.0  174.602646
13     13  4478.0        5.0  699900.0  156.297454
14     14  1268.0        3.0  259900.0  204.968454
15     15  2300.0        4.0  449900.0  195.608696
16     16  1320.0        2.0  299900.0  227.196970
17     17  1236.0        3.0  199900.0  161.731392
18     18  2609.0        4.0  499998.0  191.643542
19     19  3031.0        4.0  599000.0  197.624546
20     20  1767.0        3.0  252900.0  143.123939
21     21  1888.0        2.0  255000.0  135.063559
22     22  1604.0        3.0  242900.0  151.433915
23     23  1962.0        4.0  259900.0  132.466871
24     24  3890.0        3.0  573900.0  147.532134
25     25  1100.0        3.0  249900.0  227.181818
26     26  1458.0        3.0  464500.0  318.587106
27     27  2526.0        3.0  469000.0  185.669042
28     28  2200.0        3.0  475000.0  215.909091
29     29  2637.0        3.0  299900.0  113.727721
30     30  1839.0        2.0  349900.0  190.266449
31     31  1000.0        1.0  169900.0  169.900000
32     32  2040.0        4.0  314900.0  154.362745
33     33  3137.0        3.0  579900.0  184.858145
34     34  1811.0        4.0  285900.0  157.868581
35     35  1437.0        3.0  249900.0  173.903967
36     36  1239.0        3.0  229900.0  185.552865
37     37  2132.0        4.0  345000.0  161.819887
38     38  4215.0        4.0  549000.0  130.249110
39     39  2162.0        4.0  287000.0  132.747456
40     40  1664.0        2.0  368500.0  221.454327
41     41  2238.0        3.0  329900.0  147.408400
42     42  2567.0        4.0  314000.0  122.321776
43     43  1200.0        3.0  299000.0  249.166667
44     44   852.0        2.0  179900.0  211.150235
45     45  1852.0        4.0  299900.0  161.933045
46     46  1203.0        3.0  239500.0  199.085619

In [17]:
# so now lets think what we need from this table to think of a good house...
# area bathroom ?
# okay lets drop the rest of the stuff from the table and keep those.
dataframe = dataframe.drop(["index", "price", "sq_price"], axis=1)
# We'll only use the first 10 rows of the dataset in this example
dataframe = dataframe[0:10]
dataframe

area  bathrooms
0  2104.0        3.0
1  1600.0        3.0
2  2400.0        3.0
3  1416.0        2.0
4  3000.0        4.0
5  1985.0        4.0
6  1534.0        3.0
7  1427.0        3.0
8  1380.0        3.0
9  1494.0        3.0

In [18]:
# perfect , we have our features, now we need labels.
# labels are something like GOOD/BAD... True false, 0/1 
#lets say the first row is a good house, we give it lables 1
dataframe.loc[:, ("y1")] = [1, 1, 1, 0, 0, 1, 0, 1, 1, 1] 
                                                         
dataframe.loc[:, ("y2")] = dataframe["y1"] == 0           
dataframe.loc[:, ("y2")] = dataframe["y2"].astype(int)
dataframe # How is our dataframe looking now?
# you actually dont need to make it y1 ,  y2 but this for future purpose - SPECIALLY FOR ME 

area  bathrooms  y1  y2
0  2104.0        3.0   1   0
1  1600.0        3.0   1   0
2  2400.0        3.0   1   0
3  1416.0        2.0   0   1
4  3000.0        4.0   0   1
5  1985.0        4.0   1   0
6  1534.0        3.0   0   1
7  1427.0        3.0   1   0
8  1380.0        3.0   1   0
9  1494.0        3.0   1   0

In [19]:
# so now we have our features and labels...
# we need it ready for tensor flow. 
#lets make them matrices
inputX = dataframe.loc[:, ['area', 'bathrooms']].as_matrix()
inputY = dataframe.loc[:, ["y1", "y2"]].as_matrix()


In [20]:
inputX # weird numbers but trust me it works!

array([[  2.10400000e+03,   3.00000000e+00],
       [  1.60000000e+03,   3.00000000e+00],
       [  2.40000000e+03,   3.00000000e+00],
       [  1.41600000e+03,   2.00000000e+00],
       [  3.00000000e+03,   4.00000000e+00],
       [  1.98500000e+03,   4.00000000e+00],
       [  1.53400000e+03,   3.00000000e+00],
       [  1.42700000e+03,   3.00000000e+00],
       [  1.38000000e+03,   3.00000000e+00],
       [  1.49400000e+03,   3.00000000e+00]])

In [21]:
inputY # see the labels!

array([[1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0]])

In [35]:
# hyper parameters for tensor flow.... umm google it :P 
learning_rate = 0.000001
training_epochs = 2000 # how many for loops we do to train it
display_step = 50 # debugger, so we display whats up every 50/ from the 2000 above
n_samples = inputY.size # how big is the size of the sample ---- should be 20 ( y1  , y2)
n_samples

20

In [41]:
x = tf.placeholder(tf.float32, [None, 2])   # Okay TensorFlow, we'll feed you an array of examples. Each example will
                                            # be an array of two float values (area, and number of bathrooms).
                                            # "None" means we can feed you any number of examples
                                            # Notice we haven't fed it the values yet
            
W = tf.Variable(tf.zeros([2, 2]))           # Maintain a 2 x 2 float matrix for the weights that we'll keep updating 
                                            # through the training process (make them all zero to begin with)
    
b = tf.Variable(tf.zeros([2]))              # Also maintain two bias values

y_values = tf.add(tf.matmul(x, W), b)       # The first step in calculating the prediction would be to multiply
                                            # the inputs matrix by the weights matrix then add the biases
    
y = tf.nn.softmax(y_values)                 # Then we use softmax as an "activation function" that translates the
                                            # numbers outputted by the previous layer into probability form
    
y_ = tf.placeholder(tf.float32, [None,2])   # For training purposes, we'll also feed you a matrix of labels

In [47]:
# Cost function: Mean squared error
cost = tf.reduce_sum(tf.pow(y_ - y, 2))/(2*n_samples)
# Gradient descent
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

In [48]:
# Initialize variabls and tensorflow session
init = tf.initialize_all_variables()
sess = tf.Session()
sess.run(init)

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [49]:
#oh shit it is starting to work :D
for i in range(training_epochs):  
    sess.run(optimizer, feed_dict={x: inputX, y_: inputY}) # Take a gradient descent step using our inputs and labels

    # That's all! The rest of the cell just outputs debug messages. 
    # Display logs per epoch step
    if (i) % display_step == 0:
        cc = sess.run(cost, feed_dict={x: inputX, y_:inputY})
        print("Training step:", '%04d' % (i), "cost=", "{:.9f}".format(cc)) #, \"W=", sess.run(W), "b=", sess.run(b)

print("Optimization Finished!")
training_cost = sess.run(cost, feed_dict={x: inputX, y_: inputY})
print("Training cost=", training_cost, "W=", sess.run(W), "b=", sess.run(b), '\n')

Training step: 0000 cost= 0.125000000
Training step: 0050 cost= 0.124999739
Training step: 0100 cost= 0.124999501
Training step: 0150 cost= 0.124999240
Training step: 0200 cost= 0.124999002
Training step: 0250 cost= 0.124998733
Training step: 0300 cost= 0.124998495
Training step: 0350 cost= 0.124998234
Training step: 0400 cost= 0.124997996
Training step: 0450 cost= 0.124997735
Training step: 0500 cost= 0.124997497
Training step: 0550 cost= 0.124997243
Training step: 0600 cost= 0.124996997
Training step: 0650 cost= 0.124996744
Training step: 0700 cost= 0.124996498
Training step: 0750 cost= 0.124996245
Training step: 0800 cost= 0.124995992
Training step: 0850 cost= 0.124995746
Training step: 0900 cost= 0.124995492
Training step: 0950 cost= 0.124995247
Training step: 1000 cost= 0.124994993
Training step: 1050 cost= 0.124994740
Training step: 1100 cost= 0.124994494
Training step: 1150 cost= 0.124994241
Training step: 1200 cost= 0.124993995
Training step: 1250 cost= 0.124993742
Training ste

In [34]:
# training done!
# now lets see how good it is doing...
sess.run(y, feed_dict={x: inputX })

array([[ 0.71125221,  0.28874779],
       [ 0.66498977,  0.33501023],
       [ 0.73657656,  0.26342347],
       [ 0.64718789,  0.35281211],
       [ 0.78335613,  0.2166439 ],
       [ 0.70069474,  0.29930523],
       [ 0.65866327,  0.34133676],
       [ 0.64828628,  0.35171372],
       [ 0.64368278,  0.35631716],
       [ 0.65480113,  0.3451989 ]], dtype=float32)

In [46]:
# :( got 7/10 right.... okay we can improve this shit ...
# next time :P Gotta learn how haha.

